import React, { useState } from "react";
import axios from "axios";
import { toast } from "react-toastify";
import { Code, CheckCircle, AlertCircle, Send, Loader2 } from "lucide-react";
import { addBlog } from "./blogApi";

const BlogJsonForm = ({ onSuccess }) => {
  const [jsonInput, setJsonInput] = useState("");
  const [isValid, setIsValid] = useState(null);
  const [loading, setLoading] = useState(false);

  const validateJson = () => {
    if (!jsonInput.trim()) {
      toast.info("Input area is empty.");
      return;
    }
    try {
      JSON.parse(jsonInput);
      setIsValid(true);
      toast.success("JSON is valid!");
    } catch (error) {
      setIsValid(false);
      toast.error("Invalid JSON format.");
    }
  };

  const handleSubmit = async () => {
    if (!jsonInput.trim()) {
      toast.warning("Please paste blog JSON first.");
      return;
    }

    let parsedData;
    try {
      parsedData = JSON.parse(jsonInput);
    } catch (error) {
      toast.error("Invalid JSON. Please validate before submitting.");
      return;
    }

    setLoading(true);
    try {
      const response = await addBlog(parsedData);
      if (response.status === 200 || response.status === 201) {
        toast.success("Blog added successfully!");
        setJsonInput("");
        setIsValid(null);
        if (onSuccess) onSuccess();
      }
    } catch (error) {
      console.error("Submit Error:", error);
      toast.error(error.message || "Failed to add blog. Server error.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-200">
      <div className="flex items-center gap-2 mb-4">
        <div className="p-2 bg-orange-100 rounded-lg">
          <Code className="text-orange-600" size={24} />
        </div>
        <h2 className="text-xl font-semibold text-gray-800">
          Add Blog via JSON
        </h2>
      </div>

      <p className="text-sm text-gray-500 mb-4">
        Paste the blog JSON generated by Claude AI below. Make sure it matches
        the brand guidelines for <b>Rajlakshmi Javiks</b>.
      </p>

      <div className="relative">
        <textarea
          value={jsonInput}
          onChange={(e) => {
            setJsonInput(e.target.value);
            setIsValid(null);
          }}
          placeholder='{ "title": "Example Blog", "category": "Dairy", "author": "Admin", "read_time": "5 min", "content": "..." }'
          className={`w-full h-80 p-4 font-mono text-sm bg-gray-50 border rounded-lg focus:ring-2 focus:ring-orange-200 transition-all outline-none ${
            isValid === true
              ? "border-green-500 ring-2 ring-green-50"
              : isValid === false
                ? "border-red-500 ring-2 ring-red-50"
                : "border-gray-200"
          }`}
        />
        <div className="absolute bottom-4 right-4 flex gap-2">
          {isValid === true && (
            <div className="bg-green-100 text-green-600 px-3 py-1 rounded-full text-xs font-bold flex items-center gap-1">
              <CheckCircle size={14} /> VALID
            </div>
          )}
          {isValid === false && (
            <div className="bg-red-100 text-red-600 px-3 py-1 rounded-full text-xs font-bold flex items-center gap-1">
              <AlertCircle size={14} /> ERROR
            </div>
          )}
        </div>
      </div>

      <div className="mt-6 flex flex-col sm:flex-row gap-4">
        <button
          onClick={validateJson}
          className="flex-1 px-6 py-4 bg-white border border-gray-200 hover:bg-gray-50 text-gray-700 font-semibold rounded-xl flex items-center justify-center gap-2 transition-all shadow-sm"
        >
          <CheckCircle size={18} />
          Validate JSON
        </button>
        <button
          onClick={handleSubmit}
          disabled={loading}
          className="flex-1 px-6 py-4 bg-orange-600 hover:bg-orange-700 text-white font-semibold rounded-xl flex items-center justify-center gap-2 transition-all shadow-lg shadow-orange-100 disabled:opacity-70"
        >
          {loading ? (
            <Loader2 className="animate-spin" size={20} />
          ) : (
            <Send size={20} />
          )}
          Submit Blog
        </button>
      </div>
    </div>
  );
};

export default BlogJsonForm;
